name: Publish to Cloudflare

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cloudflare-pages-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Install TailwindCSS Forms
        run: |
          npm install -D @tailwindcss/forms

      - name: Build the Rust WASM app and all of its assets
        run: |
          trunk build --release

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: './dist'
          gitHubToken: ${{ secrets.GH_TOKEN }}